version: '3'

services:
  webhook:
    container_name: webhook
    image: almir/webhook
    ports:
      - 9000:9000
    command: -verbose -hotreload
    volumes:
      - ./hooks.json:/etc/webhook/hooks.json
      - ./scripts:/etc/scripts
      - ./storage:/storage
    networks:
      - customNetwork

  testContainer:
    container_name: testContainer
    image: mikesir87/ubuntu-with-curl
    command: tail -f /dev/null
    volumes:
      - ./append-text:/usr/bin/append-text
      - ./exampleFile.txt:/exampleFile.txt
      - ./staticToken.txt:/staticToken.txt
    networks:
      - customNetwork

networks:
  customNetwork:
